// <auto-generated />
namespace STEM_Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class STEM2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(STEM2));
        
        string IMigrationMetadata.Id
        {
            get { return "201604081634410_STEM2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
